Try out label.
edx/django-wiki pull request #23
Opened 2017-02-07 16:25 UTC by cahrens

2017-02-08 14:56 UTC, cahrens commented on wiki/templates/wiki/dir.html
> +  <div class="pull-right input-prepend">
Add ?w=1 to suppress whitespace differences (though note that then you won't see comments or be able to create them).

2017-02-08 15:01 UTC, cahrens commented on wiki/templates/wiki/dir.html
> +    {% if filter_query %}
Previously "(clear)" was appearing to the left of the input field when it displayed.

![image](https://cloud.githubusercontent.com/assets/484484/22742671/8a98acec-ede5-11e6-9539-89290353dca3.png)

2017-02-08 15:01 UTC, cahrens commented on wiki/templates/wiki/dir.html
> +{% if directory %}
Only add the table if there are filter results.

2017-02-08 18:28 UTC, jlajoie commented
Looks good to me :+1:

2017-02-08 18:29 UTC, staubina commented
👍

2017-02-09 17:24 UTC, cptvitamin requested changes

2017-02-09 17:24 UTC, cptvitamin commented on wiki/templates/wiki/dir.html
> +      <th>{% trans "Title" %}</th>
@cahrens can you add ```scope="col"``` to each of these ```<th>``` elements?

2017-02-09 20:32 UTC, cahrens commented on wiki/templates/wiki/dir.html
> +      <th>{% trans "Title" %}</th>
Yep, will do so.

2017-02-10 14:36 UTC, cahrens commented
@cptvitamin I did add scope="col". Going ahead and merging.

2017-02-10 14:36 UTC, merged

2017-02-10 21:16 UTC, cptvitamin commented
👍